import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "sq" | "fr" | "en";

type Copy = {
  meta: { title: string; description: string };
  nav: { work: string; services: string; method: string; about: string; contact: string; quote: string; menu: string; close: string; language: string };
  hero: { eyebrow: string; title: string; description: string; primary: string; secondary: string; points: string[] };
  work: { eyebrow: string; title: string; intro: string; client: string; visit: string; conceptTitle: string; conceptBadge: string; conceptDescription: string; conceptVisit: string; projects: { name: string; category: string; description: string; alt: string }[] };
  services: { eyebrow: string; title: string; intro: string; items: { title: string; description: string }[]; note: string };
  method: { eyebrow: string; title: string; steps: { title: string; description: string }[]; ai: string };
  about: { eyebrow: string; title: string; paragraphs: string[] };
  faq: { eyebrow: string; title: string; items: { question: string; answer: string }[] };
  contact: { eyebrow: string; title: string; text: string; unavailable: string; direct: string };
  footer: { description: string; region: string; signature: string; legal: string; privacy: string };
  legal: { title: string; intro: string; knownTitle: string; known: string[]; missingTitle: string; missing: string; contact: string };
  privacy: { title: string; intro: string; currentTitle: string; current: string; missingTitle: string; missing: string; contact: string };
  notFound: { title: string; text: string; home: string };
  thankYou: { title: string; invalid: string; home: string; work: string };
  common: { required: string; optional: string; external: string };
};

const projects = {
  sq: [
    { name: "Glam Fashion House", category: "Modë • Kosovë", description: "Dyqan online për një markë mode, me koleksione dhe produkte të prezantuara qartë.", alt: "Pamje e faqes Glam Fashion House me koleksionet e modës" },
    { name: "BRIZIBATIMENT", category: "Ndërtimtari • Francë", description: "Faqe profesionale për asistencë në ekspertizën e ndërtesave, shërbimet dhe partnerët.", alt: "Pamje e faqes profesionale BRIZIBATIMENT" },
    { name: "Ergo Plus Clinic", category: "Shëndetësi • Kosovë", description: "Faqe prezantuese në shqip për një klinikë ergoterapie, shërbimet dhe informacionet praktike.", alt: "Pamje e faqes në shqip të Ergo Plus Clinic" },
  ],
  fr: [
    { name: "Glam Fashion House", category: "Mode • Kosovo", description: "Boutique en ligne pour une marque de mode, avec ses collections et ses produits.", alt: "Aperçu du site Glam Fashion House présentant ses collections de mode" },
    { name: "BRIZIBATIMENT", category: "Bâtiment • France", description: "Site professionnel d’assistance à l’expertise bâtiment, présentant les services et partenaires.", alt: "Aperçu du site professionnel BRIZIBATIMENT" },
    { name: "Ergo Plus Clinic", category: "Santé • Kosovo", description: "Site vitrine en albanais d’une clinique d’ergothérapie, avec services et informations pratiques.", alt: "Aperçu du site albanais d’Ergo Plus Clinic" },
  ],
  en: [
    { name: "Glam Fashion House", category: "Fashion • Kosovo", description: "An online store for a fashion brand, presenting its collections and products.", alt: "Preview of the Glam Fashion House website and its fashion collections" },
    { name: "BRIZIBATIMENT", category: "Construction • France", description: "A professional building expertise support website presenting services and partners.", alt: "Preview of the professional BRIZIBATIMENT website" },
    { name: "Ergo Plus Clinic", category: "Healthcare • Kosovo", description: "An Albanian-language website for an occupational therapy clinic, with services and practical information.", alt: "Preview of the Albanian-language Ergo Plus Clinic website" },
  ],
};

export const translations: Record<Language, Copy> = {
  sq: {
    meta: { title: "TADAM | Krijim faqesh interneti në Kosovë", description: "Adhurim Mustafa krijon faqe prezantuese, katalogë produktesh dhe dyqane online me mbështetje personale. Kosovë dhe bashkëpunim në distancë." },
    nav: { work: "Projektet", services: "Shërbimet", method: "Si punoj", about: "Rreth meje", contact: "Kontakt", quote: "Kërko ofertë", menu: "Hap menynë", close: "Mbyll menynë", language: "Zgjidh gjuhën" },
    hero: { eyebrow: "Krijim faqesh interneti • Kosovë dhe në distancë", title: "Një faqe profesionale që përfaqëson biznesin tuaj.", description: "Krijoj faqe interneti për dyqane, zejtarë dhe biznese shërbimesh. Nga ideja e parë deri te publikimi, komunikojmë drejtpërdrejt për një faqe të qartë, të punuar me kujdes dhe të përshtatur për ju.", primary: "Kërko ofertë", secondary: "Shiko projektet", points: ["Kontakt i drejtpërdrejtë", "Faqe e përshtatur për telefon", "Ofertë sipas nevojave tuaja"] },
    work: { eyebrow: "Projektet", title: "Projekte konkrete nga fusha të ndryshme.", intro: "Një përzgjedhje faqesh të krijuara për aktivitete në Kosovë dhe në Francë.", client: "Projekt për klient", visit: "Shiko faqen", conceptTitle: "Koncept faqeje", conceptBadge: "Propozim për biznes", conceptDescription: "Koncept për të prezantuar një aktivitet kateringu, shërbime për evente dhe ushqime. Projekti u propozua, por prospekti nuk dha përgjigje.", conceptVisit: "Shiko konceptin", projects: projects.sq },
    services: { eyebrow: "Shërbimet", title: "Një faqe sipas nevojave të biznesit tuaj.", intro: "Formati i duhur varet nga ajo që vizitorët tuaj duhet të zbulojnë ose të bëjnë.", items: [{ title: "Faqe prezantuese", description: "Prezantoni biznesin, shërbimet dhe kontaktet tuaja në telefon dhe kompjuter." }, { title: "Katalog produktesh", description: "Paraqitni koleksionet ose produktet dhe merrni kërkesa kontakti, pa pagesa online." }, { title: "Dyqan online", description: "Shitje në internet; pagesat, porositë, stoku dhe dërgesat përcaktohen së bashku para ofertës." }], note: "Numri i faqeve, gjuhët, funksionalitetet dhe mbështetja përcaktohen në çdo propozim." },
    method: { eyebrow: "Si punoj", title: "Mbështetje e qartë, hap pas hapi.", steps: [{ title: "Kuptoj nevojën tuaj", description: "Bisedojmë për aktivitetin, klientët dhe objektivin tuaj." }, { title: "Përcaktojmë projektin", description: "Përcaktojmë përmbajtjen, çmimin dhe afatin sipas nevojave." }, { title: "Krijojmë dhe përmirësojmë", description: "Përgatis faqen dhe i shqyrtojmë së bashku komentet tuaja." }, { title: "Kontrollojmë dhe publikojmë", description: "Pas miratimit dhe kontrolleve, faqja publikohet; udhëzimi dhe vazhdimësia përcaktohen në ofertë." }], ai: "Përdor mjete moderne, përfshirë inteligjencën artificiale, për të mbështetur procesin krijues. Unë mbetem përgjegjës për zgjedhjet e dizajnit, kontrollet dhe vazhdimësinë." },
    about: { eyebrow: "Rreth meje", title: "Kontakti juaj: Adhurim Mustafa.", paragraphs: ["Jam krijuesi i TADAM. Kam realizuar faqe interneti në modë, ndërtimtari dhe shëndetësi. Ju shoqëroj personalisht, me komunikim të drejtpërdrejtë gjatë gjithë projektit.", "Ofroj shërbime për biznese në Kosovë dhe punoj në distancë, veçanërisht me klientë në Francë."] },
    faq: { eyebrow: "FAQ", title: "Përgjigje të qarta për pyetjet tuaja.", items: [{ question: "Sa kushton një faqe interneti?", answer: "Çmimi varet nga numri i faqeve, gjuhët dhe funksionalitetet. Pas bisedës së parë përgatis një ofertë sipas nevojave tuaja." }, { question: "Sa kohë duhet?", answer: "Afati varet nga projekti dhe përcaktohet para fillimit." }, { question: "Çfarë duhet të siguroj?", answer: "Informacionet për aktivitetin, kontaktet, logon dhe përmbajtjet që keni në dispozicion." }, { question: "A mund të jetë faqja në disa gjuhë?", answer: "Po. Gjuhët dhe përmbajtjet përcaktohen në kuadër të projektit." }, { question: "A ka shpenzime pas krijimit?", answer: "Domeni dhe hostimi janë shpenzime të ndara nga çmimi i krijimit." }, { question: "Kujt i përkasin domeni dhe qasjet?", answer: "Pronësia dhe mënyra e dorëzimit të qasjeve përcaktohen para fillimit." }, { question: "A përfshihen ndryshimet dhe mirëmbajtja?", answer: "Korrigjimet e përfshira përshkruhen në ofertë. Kërkesat e reja vlerësohen veçmas." }, { question: "A punoni në distancë?", answer: "Po. Punoj me biznese në Kosovë dhe në distancë, përfshirë Francën." }] },
    contact: { eyebrow: "Kontakt", title: "Le të flasim për projektin tuaj.", text: "Më tregoni për aktivitetin tuaj dhe atë që dëshironi të krijoni. Do t’ju kontaktoj për të sqaruar nevojën dhe për të përgatitur një propozim.", unavailable: "Për të më treguar për projektin tuaj, më shkruani drejtpërdrejt me email.", direct: "Më shkruani me email" },
    footer: { description: "Krijim faqesh interneti me mbështetje personale.", region: "Kosovë • Bashkëpunim në distancë, përfshirë Francën.", signature: "Magjia e thjeshtësisë.", legal: "Informacione ligjore", privacy: "Privatësia" },
    legal: { title: "Informacione ligjore", intro: "Kjo faqe përmbledh vetëm informacionet e konfirmuara për TADAM.", knownTitle: "Informacione të konfirmuara", known: ["Emri tregtar: TADAM", "Krijuesi dhe kontakti: Adhurim Mustafa", "Email: adhurimustafa@gmail.com"], missingTitle: "Informacione për t’u konfirmuar para publikimit", missing: "Statusi juridik, numri i regjistrimit, adresa ligjore dhe të dhënat ligjore të hostimit nuk janë konfirmuar ende. Asnjë e dhënë nuk është shpikur.", contact: "Për çdo pyetje, kontaktoni Adhurim Mustafa me email." },
    privacy: { title: "Privatësia", intro: "Kjo faqe shpjegon trajtimin aktual të të dhënave në këtë version të faqes.", currentTitle: "Trajtimi aktual", current: "Nuk përdoren mjete analitike ose gjurmues marketingu. Formulari publik është i çaktivizuar derisa transmetimi i sigurt të jetë funksional; kontakti bëhet me lidhjen e emailit.", missingTitle: "Për t’u përcaktuar para aktivizimit të formularit", missing: "Qëllimet e plota, baza ligjore, afati i ruajtjes dhe ofruesit do të dokumentohen sipas sistemit real të zgjedhur.", contact: "Për pyetje mbi privatësinë, shkruani në adhurimustafa@gmail.com." },
    notFound: { title: "Faqja nuk u gjet", text: "Kjo faqe nuk ekziston ose është zhvendosur.", home: "Kthehu në ballinë" },
    thankYou: { title: "Kërkesa u dërgua", invalid: "Nuk ka asnjë kërkesë të konfirmuar. Ju lutem, përdorni kontaktin në faqen kryesore.", home: "Kthehu në ballinë", work: "Shiko projektet" },
    common: { required: "e detyrueshme", optional: "fakultative", external: "hapet në një skedë të re" },
  },
  fr: {
    meta: { title: "TADAM | Création de sites internet au Kosovo", description: "Adhurim Mustafa crée votre site vitrine, catalogue ou boutique en ligne avec un accompagnement personnel. Kosovo et collaboration à distance." },
    nav: { work: "Réalisations", services: "Services", method: "Ma méthode", about: "À propos", contact: "Contact", quote: "Demander un devis", menu: "Ouvrir le menu", close: "Fermer le menu", language: "Choisir la langue" },
    hero: { eyebrow: "Création de sites internet • Kosovo et à distance", title: "Un site professionnel à l’image de votre entreprise.", description: "Je crée des sites pour boutiques, artisans et entreprises de services. De la première idée à la mise en ligne, nos échanges sont directs pour créer un site clair, soigné et adapté à votre activité.", primary: "Demander un devis", secondary: "Voir mes réalisations", points: ["Un interlocuteur direct", "Un site adapté au mobile", "Un devis selon vos besoins"] },
    work: { eyebrow: "Réalisations", title: "Des projets concrets, dans différents secteurs.", intro: "Une sélection de sites créés pour des activités au Kosovo et en France.", client: "Réalisation client", visit: "Voir le site", conceptTitle: "Concept de site", conceptBadge: "Proposition commerciale", conceptDescription: "Concept de site pour présenter une activité de traiteur, ses prestations événementielles et ses repas. Le projet a été proposé, mais le prospect n’a pas donné suite.", conceptVisit: "Voir le concept", projects: projects.fr },
    services: { eyebrow: "Services", title: "Un site adapté à votre activité.", intro: "Le bon format dépend de ce que vos visiteurs doivent découvrir ou faire.", items: [{ title: "Site vitrine", description: "Présentez votre entreprise, vos services et vos coordonnées sur téléphone comme sur ordinateur." }, { title: "Catalogue de produits", description: "Présentez vos collections ou produits et recevez des demandes de contact, sans paiement en ligne." }, { title: "Boutique en ligne", description: "Vendez sur internet ; paiements, commandes, stocks et livraison sont définis ensemble avant le devis." }], note: "Le nombre de pages, les langues, les fonctionnalités et l’accompagnement sont précisés dans chaque proposition." },
    method: { eyebrow: "Ma méthode", title: "Un accompagnement clair, étape par étape.", steps: [{ title: "Comprendre votre besoin", description: "Nous échangeons sur votre activité, vos clients et votre objectif." }, { title: "Définir le projet", description: "Je précise un périmètre, un prix et un calendrier adaptés." }, { title: "Créer et ajuster", description: "Je prépare le site et nous examinons ensemble vos retours." }, { title: "Vérifier et mettre en ligne", description: "Après validation et vérifications, le site est mis en ligne. La prise en main et le suivi sont précisés dans le devis." }], ai: "J’utilise des outils modernes, dont l’intelligence artificielle, pour m’aider dans la création. Je reste responsable des choix de conception, des vérifications et du suivi." },
    about: { eyebrow: "À propos", title: "Votre interlocuteur : Adhurim Mustafa.", paragraphs: ["Je suis le créateur de TADAM. J’ai réalisé des sites dans la mode, le bâtiment et la santé. Je vous accompagne personnellement, avec des échanges directs tout au long du projet.", "Je propose mes services aux entreprises au Kosovo et travaille à distance, notamment avec des clients en France."] },
    faq: { eyebrow: "FAQ", title: "Vos questions, simplement.", items: [{ question: "Combien coûte un site internet ?", answer: "Le prix dépend du nombre de pages, des langues et des fonctionnalités. Je prépare un devis après un premier échange." }, { question: "Quel est le délai de création ?", answer: "Le délai dépend du projet et vous est précisé avant le démarrage." }, { question: "Que dois-je fournir ?", answer: "Les informations sur votre activité, vos coordonnées, votre logo et les contenus déjà disponibles." }, { question: "Le site peut-il être multilingue ?", answer: "Oui, selon le périmètre défini pour le projet." }, { question: "Y a-t-il des frais après la création ?", answer: "Le domaine et l’hébergement sont distincts du prix de création." }, { question: "À qui appartiennent le domaine et les accès ?", answer: "La titularité du domaine et les modalités d’accès sont définies avant le démarrage." }, { question: "Les modifications et la maintenance sont-elles incluses ?", answer: "Les retouches incluses figurent dans le devis. Les nouvelles demandes sont évaluées séparément." }, { question: "Travaillez-vous à distance ?", answer: "Oui, avec des entreprises au Kosovo et à distance, notamment en France." }] },
    contact: { eyebrow: "Contact", title: "Parlons de votre projet.", text: "Présentez-moi votre activité et ce que vous souhaitez créer. Je vous recontacterai pour préciser le besoin et préparer une proposition.", unavailable: "Pour me parler de votre projet, écrivez-moi directement par email.", direct: "M’écrire par email" },
    footer: { description: "Création de sites internet avec accompagnement personnel.", region: "Kosovo • Collaboration à distance, notamment en France.", signature: "La magie de la simplicité.", legal: "Mentions légales", privacy: "Confidentialité" },
    legal: { title: "Mentions légales", intro: "Cette page réunit uniquement les informations confirmées concernant TADAM.", knownTitle: "Informations confirmées", known: ["Nom commercial : TADAM", "Créateur et contact : Adhurim Mustafa", "Email : adhurimustafa@gmail.com"], missingTitle: "Informations à confirmer avant publication", missing: "Le statut juridique, le numéro d’immatriculation, l’adresse légale et les mentions juridiques de l’hébergeur ne sont pas encore confirmés. Aucune donnée n’a été inventée.", contact: "Pour toute question, contactez Adhurim Mustafa par email." },
    privacy: { title: "Confidentialité", intro: "Cette page décrit le traitement actuel des données dans cette version du site.", currentTitle: "Traitement actuel", current: "Aucun outil d’analyse ni traceur marketing n’est utilisé. Le formulaire public reste désactivé tant qu’une transmission sécurisée n’est pas opérationnelle ; le contact passe par le lien email.", missingTitle: "À définir avant l’activation du formulaire", missing: "Les finalités complètes, la base légale, la durée de conservation et les prestataires seront documentés selon le système réellement retenu.", contact: "Pour toute question relative à la confidentialité, écrivez à adhurimustafa@gmail.com." },
    notFound: { title: "Page introuvable", text: "Cette page n’existe pas ou a été déplacée.", home: "Retour à l’accueil" },
    thankYou: { title: "Demande transmise", invalid: "Aucune demande confirmée n’est associée à cette page. Utilisez le contact de la page d’accueil.", home: "Retour à l’accueil", work: "Voir mes réalisations" },
    common: { required: "obligatoire", optional: "facultatif", external: "s’ouvre dans un nouvel onglet" },
  },
  en: {
    meta: { title: "TADAM | Website Creation in Kosovo", description: "Adhurim Mustafa creates business websites, product catalogues and online stores with personal support. Serving Kosovo and working remotely." },
    nav: { work: "My work", services: "Services", method: "How I work", about: "About me", contact: "Contact", quote: "Request a quote", menu: "Open menu", close: "Close menu", language: "Choose language" },
    hero: { eyebrow: "Website creation • Kosovo and remote collaboration", title: "A professional website that reflects your business.", description: "I create websites for shops, craftspeople and service businesses. From the first idea to launch, we communicate directly to create a clear, polished website tailored to your business.", primary: "Request a quote", secondary: "View my work", points: ["One direct point of contact", "A mobile-friendly website", "A quote tailored to your needs"] },
    work: { eyebrow: "My work", title: "Real projects across different sectors.", intro: "A selection of websites created for businesses in Kosovo and France.", client: "Client project", visit: "Visit website", conceptTitle: "Website concept", conceptBadge: "Business proposal", conceptDescription: "A website concept presenting a catering business, event services and meals. The project was proposed, but the prospect did not follow up.", conceptVisit: "View concept", projects: projects.en },
    services: { eyebrow: "Services", title: "A website tailored to your business.", intro: "The right format depends on what your visitors need to discover or do.", items: [{ title: "Business website", description: "Present your business, services and contact details clearly on mobile and desktop." }, { title: "Product catalogue", description: "Showcase collections or products and receive enquiries, without online payment." }, { title: "Online store", description: "Sell online; payments, orders, stock and delivery are defined together before the quote." }], note: "The number of pages, languages, features and support are detailed in each proposal." },
    method: { eyebrow: "How I work", title: "Clear support, step by step.", steps: [{ title: "Understand your needs", description: "We discuss your business, customers and objective." }, { title: "Define the project", description: "I set out a suitable scope, price and schedule." }, { title: "Create and refine", description: "I prepare the website and we review your feedback together." }, { title: "Check and launch", description: "After approval and checks, the website goes live. Handover and follow-up terms are included in the quote." }], ai: "I use modern tools, including artificial intelligence, to support the creative process. I remain responsible for the design decisions, checks and follow-up." },
    about: { eyebrow: "About me", title: "Your point of contact: Adhurim Mustafa.", paragraphs: ["I am the creator of TADAM. I have built websites in fashion, construction and healthcare. I support you personally, with direct communication throughout the project.", "I provide services to businesses in Kosovo and work remotely, particularly with clients in France."] },
    faq: { eyebrow: "FAQ", title: "Straightforward answers to your questions.", items: [{ question: "How much does a website cost?", answer: "The price depends on the number of pages, languages and features. I prepare a quote after an initial conversation." }, { question: "How long does it take?", answer: "The schedule depends on the project and is confirmed before work begins." }, { question: "What do I need to provide?", answer: "Information about your business, your contact details, logo and any content already available." }, { question: "Can the website be multilingual?", answer: "Yes, according to the agreed project scope." }, { question: "Are there costs after the website is created?", answer: "Domain and hosting costs are separate from the website creation price." }, { question: "Who owns the domain and account access?", answer: "Domain ownership and access arrangements are agreed before work begins." }, { question: "Are changes and maintenance included?", answer: "Included revisions are listed in the quote. New requests are assessed separately." }, { question: "Do you work remotely?", answer: "Yes. I work with businesses in Kosovo and remotely, including France." }] },
    contact: { eyebrow: "Contact", title: "Let's talk about your project.", text: "Tell me about your business and what you would like to create. I will contact you to clarify your needs and prepare a proposal.", unavailable: "To tell me about your project, please email me directly.", direct: "Email me" },
    footer: { description: "Website creation with personal support.", region: "Kosovo • Remote collaboration, including France.", signature: "The magic of simplicity.", legal: "Legal notice", privacy: "Privacy" },
    legal: { title: "Legal notice", intro: "This page contains only confirmed information about TADAM.", knownTitle: "Confirmed information", known: ["Trading name: TADAM", "Creator and contact: Adhurim Mustafa", "Email: adhurimustafa@gmail.com"], missingTitle: "Information to confirm before publication", missing: "Legal status, registration number, legal address and the hosting provider’s legal details have not yet been confirmed. No details have been invented.", contact: "For any question, contact Adhurim Mustafa by email." },
    privacy: { title: "Privacy", intro: "This page describes current data handling in this version of the website.", currentTitle: "Current handling", current: "No analytics or marketing trackers are used. The public form remains disabled until secure delivery is operational; contact is available through the email link.", missingTitle: "To define before enabling the form", missing: "The complete purposes, legal basis, retention period and providers will be documented according to the system actually selected.", contact: "For privacy questions, email adhurimustafa@gmail.com." },
    notFound: { title: "Page not found", text: "This page does not exist or has been moved.", home: "Back to home" },
    thankYou: { title: "Enquiry sent", invalid: "No confirmed enquiry is associated with this page. Please use the contact section on the home page.", home: "Back to home", work: "View my work" },
    common: { required: "required", optional: "optional", external: "opens in a new tab" },
  },
};

const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void; t: Copy } | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("tadam-language");
    return saved === "fr" || saved === "en" || saved === "sq" ? saved : "sq";
  });
  const setLanguage = (next: Language) => {
    localStorage.setItem("tadam-language", next);
    setLanguageState(next);
  };
  useEffect(() => {
    document.documentElement.lang = language;
    document.title = translations[language].meta.title;
    document.querySelector('meta[name="description"]')?.setAttribute("content", translations[language].meta.description);
  }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: translations[language] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}